spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssmproject?userUnicode=true&characterEncoding=utf-8&userSSL=false
    password: 121148
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: 192.168.70.131
      password: 121148
      username: default
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/project/hhRepository/mapper/*.xml

mybatis:
  mapper-locations: classpath:com/project/hhRepository/mapper/*.xml

logging:
  config: classpath:logback.xml

server:
  port: 3000

#个人自定义配置
warehouse:
  expire-time:2000
